version: '3.8'

services:
  app:
    build: .
    container_name: word-api
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env # Carrega automaticamente as variáveis do .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Usa variável do .env
      MYSQL_DATABASE: ${DB_DATABASE}     # Usa variável do .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
